# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fcbb427dadca77b8ad99252fe9dc84bba5770e9a568ba36fc9554d3b69afba890905585804fbe82ce8f3171ea75eb878b68d3404e364423ede6d68c68edc0513

test:
  secret_key_base: bb8c1a6cd81e4858c70d4ac4f3ba774aba66c4292210015194b517b1f450475899c133029718156c41e96757f6e866147454c940cec4be4d5b391f3f1b68eff3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
